name: Build-Test-Fmt

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-test-fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: rustup show
    
    - name: Install rustfmt and clippy
      run: |
        rustup component add rustfmt
        rustup component add clippy

    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build
      
    - name: Test
      run: cargo test
      
    - name: Fmt
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy -- -D warnings